version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php"
    schedule:
      interval: "daily"
